version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: reverse-eng-postgres
    environment:
      POSTGRES_DB: reverse_engineering_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reverse-eng-network

  redis:
    image: redis:7-alpine
    container_name: reverse-eng-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reverse-eng-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: reverse-eng-backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - DATABASE_URL=postgres://user:password@postgres:5432/reverse_engineering_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - reverse-eng-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: reverse-eng-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - reverse-eng-network

volumes:
  postgres_data:
  redis_data:

networks:
  reverse-eng-network:
    driver: bridge
